version: '3.9'

services:
  api:
    build:
      context: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
  
  client:
    build:
      context: ./client/logbook
    volumes:
      - react_build:/client/build

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - react_build:/var/www/client

  postgres:
    container_name: postgres
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - "C:/logbook_database:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${DB_NAME}", "-U", "${DB_USER}", "-p", "5432", "-h", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 10

volumes:
  react_build:
    name: react_build
