version: '3.9'

services:
  api:
    build:
      context: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    env_file:
      - .env
    depends_on:
      - postgres

  client:
    build:
      context: ./client/logbook
    volumes:
      - react_build:/client/build

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - react_build:/var/www/client
    depends_on:
      - api
      - client

  postgres:
    container_name: postgres
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
    name: postgres_data
  react_build:
    name: react_build
